imu_topic: "/oak/imu/data"    # IMU ROS topic
imu_rate: 400        # Rate of IMU
sequence_time: 14000            # Maximum time for analysis in seconds (1 hour)
measure_rate: 100         # Rate at which IMU data is subsampled
